# Generated by Django 2.2.1 on 2019-05-14 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_of_birth', models.IntegerField()),
                ('club', models.CharField(max_length=200)),
                ('position', models.IntegerField(choices=[(1, 'Bramkarz'), (2, 'Prawy obrońca'), (3, 'Lewy obrońca'), (4, 'Półlewy obrońca'), (5, 'Półprawy obrońca'), (6, 'Lewe skrzydło'), (7, 'Prawe skrzydło'), (8, 'Środkowy poocnik (8)'), (9, 'Defensywny pomocnik (6)'), (10, 'Rozgrywający (10)'), (11, 'Napastnik')])),
                ('status', models.IntegerField(choices=[(1, 'Odrzucony'), (2, 'Do obserwacji'), (3, 'Wzmocnienie kadry'), (4, 'TOP')])),
                ('agent', models.TextField(verbose_name='Kontakt z agentem')),
                ('other1', models.TextField(verbose_name='Uwagi')),
                ('other2', models.TextField(verbose_name='Uwagi')),
                ('other3', models.TextField(verbose_name='Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('match', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.IntegerField(choices=[(1, 'Na żywo'), (2, 'Wideo')])),
                ('first_desc', models.TextField(verbose_name='Gra w ofensywie')),
                ('second_desc', models.TextField(verbose_name='Gra w defensywie')),
                ('third_desc', models.TextField(verbose_name='Gra bez piłki')),
                ('fourth_desc', models.TextField(verbose_name='Cechy wolicjonalne')),
                ('fifth_desc', models.TextField(verbose_name='Inne')),
                ('sixth_desc', models.TextField(verbose_name='Wnioski')),
                ('one', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Technika użytkowa')),
                ('two', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Gra słabszą nogą')),
                ('three', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Siła')),
                ('four', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Koordynacja')),
                ('five', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Przyspieszenie')),
                ('six', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Agresja')),
                ('seven', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Odpowiedzialność w grze')),
                ('eight', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Skłonność do przecinania linii przeciwnika(wejściem/podaniem)')),
                ('nine', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Pracowitość')),
                ('ten', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Odbiór piłki')),
                ('eleven', models.IntegerField(choices=[(1, '1'), (1.5, '1,5'), (2, '2'), (2.5, '2,5'), (3, '3'), (3.5, '3,5'), (4, '4')], verbose_name='Gra w powietrzu')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Box.Player')),
                ('scout', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
