# Generated by Django 2.2.3 on 2019-08-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='agent',
        ),
    ]
