# Generated by Django 2.2.1 on 2019-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='agent',
            field=models.TextField(blank=True, null=True, verbose_name='Kontakt z agentem'),
        ),
        migrations.AlterField(
            model_name='player',
            name='other1',
            field=models.TextField(blank=True, null=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='player',
            name='other2',
            field=models.TextField(blank=True, null=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='player',
            name='other3',
            field=models.TextField(blank=True, null=True, verbose_name='Uwagi'),
        ),
    ]
