# Generated by Django 2.2.1 on 2019-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0002_auto_20190514_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
