# Generated by Django 2.2.3 on 2019-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0002_remove_player_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
        migrations.AddField(
            model_name='player',
            name='agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
