# Generated by Django 2.2.3 on 2019-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0003_auto_20190806_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
