# Generated by Django 2.2.6 on 2019-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0003_observationlist_scout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationform',
            name='eight',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Skłonność do przecinania linii przeciwnika(wejściem/podaniem)'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='eleven',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Gra w powietrzu'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='five',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Przyspieszenie'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='four',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Koordynacja'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='nine',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Pracowitość'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='one',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Technika użytkowa'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='seven',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Odpowiedzialność w grze'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='six',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Agresja'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='ten',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Odbiór piłki'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='three',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Siła'),
        ),
        migrations.AlterField(
            model_name='observationform',
            name='two',
            field=models.FloatField(choices=[(1, '1 - bardzo słabo'), (1.5, '1,5'), (2, '2'), (2.5, '2,5 - przeciętnie'), (3, '3'), (3.5, '3,5'), (4, '4 - bardzo dobrze')], verbose_name='Gra słabszą nogą'),
        ),
        migrations.AlterField(
            model_name='observationlist',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
