# Generated by Django 2.2.6 on 2019-10-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0004_auto_20191020_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObservationList',
        ),
    ]
