# Generated by Django 2.2.1 on 2019-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0005_auto_20190515_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationlist',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
