# Generated by Django 2.2.1 on 2019-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0006_auto_20190516_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationlist',
            name='date',
            field=models.DateTimeField(max_length=200),
        ),
    ]
