# Generated by Django 2.2.6 on 2019-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0006_observationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationlist',
            name='date',
            field=models.DateTimeField(max_length=200),
        ),
    ]
