# Generated by Django 2.2.1 on 2019-05-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0007_auto_20190516_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='other1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='other2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='other3',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Box.Player')),
            ],
        ),
    ]
