version: '3'

services:

  box:
    build: ScoutingBox
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: coderslab
    ports:
      - '5432:5432'